name: Workflow Runners

on:
  push:
  workflow_dispatch:

jobs:
  echo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Show the OS
        run: |
          echo "This job runs on Ubuntu"
          echo "The OS is $RUNNER_OS"
  echo-windows:
    runs-on: windows-latest
    steps:
      - name: Show the OS
        shell: pwsh
        run: |
          echo "This job runs on Windows"
          echo "The OS is $RUNNER_OS"
